### PR TITLE
Remove Fetched Properties from channel and message models

### PR DESCRIPTION
**Pull request by 72A12F4E**
cleaned up from https://github.com/meshtastic/Meshtastic-Apple/pull/824 which included merge commits & app icon updates

@ChrDel-2 and @garthvh are the original authors of the changes

### CODE REVIEW

**Review by garthvh — APPROVED** [review]
Looks good I will deploy a test flight build

**Comment by garthvh** [comment]
@72A12F4E The Fetched properties in core data were essentially the same as the predicates being used now.

**Review by ChrDel — APPROVED** [review]
Looks good to me!
Thank you for opening a PR for this!
🙏

**Comment by 72A12F4E** [comment]
The message list view is kinda borked still tho

Discussion in discord for a fix

**Comment by 72A12F4E** [comment]
We need to do a data purge or a migration to combine the timestamps as discussed in Discord, then this should work as expected. It might be necessary to explicitly add sorting as well

**Comment by garthvh** [comment]
> We need to do a data purge or a migration to combine the timestamps as discussed in Discord, then this should work as expected. It might be necessary to explicitly add sorting as well

I just removed it, messageTimestamp was always loaded in parallel

**Pull request merged**
