### PR TITLE
Add First Heard and Last Heard times to node details

### PR DESCRIPTION
**Pull request by 72A12F4E**
This change adds the last heard date to the node details screen. Unfortunately, it seems much of this data is buggy for me, and I have several nodes with lastHeard dates on Jan 1 1970, so I can't really validate that the change works on the happy path.

IMG_D7578A3F43FE-1

### CODE REVIEW

**Comment by garthvh** [comment]
Can we add the first heard as well? I added it to node info recently and it has been populating for a while

**Comment by garthvh** [comment]
If you share your location from your phone it should get time

**Comment by 72A12F4E** [comment]
IMG_C944A89BAC8E-1

@garthvh hows this?

**Review by garthvh — APPROVED** [review]
Looks great!

**Pull request merged**
