### PR TITLE
feature: add simple retry mechanism

### PR DESCRIPTION
**Pull request by Austinpayne**
Implements a simple retry mechanism similar to iMessages.

IMG_E2F6ECF29094-1

IMG_0B3B60297364-1

Closes https://github.com/meshtastic/Meshtastic-Apple/issues/456

### CODE REVIEW

**Review by garthvh — COMMENTED** [review]
Would probably be good to just make it available on the max transmission error, the rest are not really likely to be corrected on re-send.  Only maxRetransmit or timeout are likely to be fixed by trying again.

**Review by garthvh — APPROVED** [review]

**Comment by Austinpayne** [comment]
> Would probably be good to just make it available on the max transmission error, the rest are not really likely to be corrected on re-send. Only maxRetransmit or timeout are likely to be fixed by trying again.

Good point, thanks for updating!

**Comment by drewzh** [comment]
Amazing, I just saw this. One improvement suggestion however if it's possible... can you update the status of the message back to 'Waiting for acknowledgment"? When you click retry, there's no UI update and you can continue to hit the (i) button and click Retry... it's just a bit janky from a UX perspective. Great that we have this feature now as I'll be making use of this regularly, so thank you very much for the efforts spent!

**Comment by Austinpayne** [comment]
That's how it was working when I originally submitted the MR. Will investigate, seems like a bug that slipped in.

**Pull request merged**
