### PR TITLE
Address several SwiftLint issues

### PR DESCRIPTION
**Pull request by 72A12F4E**
## What Changed?

This change fixes several lint errors throughout the project, and moves the SwiftLint build phase to before compilation. 

After this change, a developer can now clone the project and run without the build failing due to lint errors! 😃 

## Details

* Ran `swiftlint --fix` to resolve many auto-correctable issues (mostly whitespace)
* Excluded the `Meshtastic/Protobufs` directory from lint, since that code is automatically generated.
* Converted some single letter method parameters to lowercase.
* Converted several instances `force_cast` to instead use `guard` or `if let` to unwrap optional values and conditionally typecast. During this change, some of the SwiftUI views became "too complex to be solved in a reasonable time", so I broke up the views into distinct sub-expressions using `@ViewBuilder`, `@MapContent`, and computed properties.

## How is it tested?

I was able to build and run the app on an iPhone 15 Pro (17.0) Simulator

### CODE REVIEW

**Comment by 72A12F4E** [comment]
@garthvh what are your thoughts on excluding the generated protobuf code from SwiftLint? I've done this in a few other projects with good results, but wanted to check with your preferences.

**Comment by garthvh** [comment]
> @garthvh what are your thoughts on excluding the generated protobuf code from SwiftLint? I've done this in a few other projects with good results, but wanted to check with your preferences.

They need to get excluded, any changes would be overwritten when changes come in

**Comment by 72A12F4E** [comment]
Perfect, then this change is good to go from my end!

**Comment by 72A12F4E** [comment]
I saw the target branch changed; would you like me to rebase this?

**Comment by garthvh** [comment]
> I saw the target branch changed; would you like me to rebase this?

Yeah then I can merge it into the working changes and deploy it to TestFlight for testing.

**Comment by 72A12F4E** [comment]
> > I saw the target branch changed; would you like me to rebase this?
> 
> Yeah then I can merge it into the working changes and deploy it to TestFlight for testing.

done! ✅

**Pull request merged**
