### PR TITLE
2.3.2 working changes

### PR DESCRIPTION
**Pull request by garthvh**
## Enhancements
* Refactor of User Defaults By @ChrDel-2 
* Optimize Mesh Map Query to handle more nodes
* Add Distance filter to the mesh map
* Add node history and route lines back to the mesh map for favorites
* Add TAK Tracker role
* Icon cleanup and simplification.
* Node list filters ( Mqtt, LoRa, Online Only, Hops Away and Device Role)
* Added Map Report to Mqtt Config
* Added wave emoji to tapbacks
* Added support for new fixed position admin messages in Mqtt Config
## Bug Fixes
* Don't allow JSON and the Client Proxy at the same time
* Handle multiple links in text messages

### CODE REVIEW

**Comment by ChrDel-2** [comment]
I figured out what was going on with the CLA, there was a mix between 2 of my github accounts. 
I have approved the CLA on all my accounts and it shows as approved now...

**Comment by garthvh** [comment]
> I figured out what was going on with the CLA, there was a mix between 2 of my github accounts. I have approved the CLA on all my accounts and it shows as approved now...

Good deal, I did revert the user default updates, seems to be having an issue with the mapLayer enum value, I am sure it is something minor.

**Comment by ChrDel-2** [comment]
> I did revert the user default updates, seems to be having an issue with the mapLayer enum value, I am sure it is something minor.

If you describe the issue you experienced, I can take a look tomorrow and see what I can figure out... 🙏

**Comment by garthvh** [comment]
> > I did revert the user default updates, seems to be having an issue with the mapLayer enum value, I am sure it is something minor.
> 
> If you describe the issue you experienced, I can take a look tomorrow and see what I can figure out... 🙏
IMG_2282

I just commented it out and added my new values to both, the code is all still there and pretty easy to add back.  Pretty easy to replicate, insta crash when changing the map layer on the mesh map

**Pull request merged**
