### PR TITLE
Allowing fixed position to be entered manually

### PR DESCRIPTION
**Pull request by ChDel**
Allowing fixed position to be entered manually

### CODE REVIEW

**Comment by ChDel** [comment]
@garthvh Let me know your thoughts on this 🙏

**Comment by garthvh** [comment]
Not real interested in allowing spoofed positions, especially with the new position precision options.

**Comment by ChDel** [comment]
> Not real interested in allowing spoofed positions, especially with the new position precision options.

Any interest in the rest of the code? I refactored part of your code and also found that the Keys enum was incomplete and therefore your function to delete all the app settings is not working as expected...

**Comment by garthvh** [comment]
Those are the map settings for the legacy mesh map, It is fine to add them, they will drop with iOS 16 support.

**Comment by ChDel** [comment]
Confused why you closed this since you mentioned it was ok to add the refactor and keys for the UserDefaults..

**Comment by garthvh** [comment]
Was not on purpose, would approve the other changes

**Comment by garthvh** [comment]
Try and reopen

**Comment by garthvh** [comment]
Looks like the branch was deleted, it won't let me re-open it

**Pull request closed without merging**
